project:
  type: book
  output-dir: docs

book:
  title: "Wendi's Learning Diary"
  author: "Wendi Li"
  date: "2023/1/30"
  chapters:
    - index.qmd
    - WEEK1.qmd
    - WEEK2.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

