project:
  type: book
  output-dir: docs

book:
  title: "Wendi's Learning Diary"
  author: "Wendi Li"
  date: "2023/1/29"
  chapters:
    - index.qmd
    - WEEK1.qmd
    - WEEK2.qmd
    - WEEK3.qmd
    - WEEK4.qmd
    - WEEK5.qmd
    - WEEK6.qmd
    - W7.qmd
    - W8.qmd
    - Reference1.qmd

  repo-url: https://github.com/ucfnlih/WD_Remote.git
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  
number-sections: False

bibliography: references.bib

comments:
  hypothesis: true
  

  

format:
  html:
    theme: [cosmo]
  pdf:
    documentclass: scrreprt

editor: visual



