project:
  type: book
  output-dir: docs

book:
  title: "Wendi's Learning Diary"
  author: "Wendi Li"
  date: "2023/1/30"
  chapters:
    - index.qmd
    - WEEK1.qmd
    - WEEK2.qmd
    - WEEK3.qmd
    - WEEK6.qmd
    - WEEK7.qmd
  repo-url: https://github.com/ucfnlih/WD_Remote.git
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

number-sections: False

bibliography: references.bib

comments:
  hypothesis: true
  

  

format:
  html:
    theme: [cosmo,minty]
  pdf:
    documentclass: scrreprt

editor: visual



